Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class AboutModel : PageModel
    {
        private readonly ILogger<AboutModel> _logger;

        public AboutModel(ILogger<AboutModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using CryptoCanuck.Models;
using System.Net.Mail; 
using System.Net;
using System.Configuration;
using System.IO;


namespace CryptoCanuck.Pages
{
    public class AdminModel : PageModel
    {
        public List<string> emails = new List<string>();
        MailMessage mailMessage = new MailMessage();
        SmtpClient _smtp = new SmtpClient();
        string teamsEmail;
        string teamsEmailPassword;
        string teamsEmailHost;
        int teamsEmailPort;
        public void OnGet() {} // OnGet()
    
        public void MessageUpdate(string message){
            using (SqlConnection myConn = new SqlConnection(Program.da.cs)){
                SqlCommand addMessage = new SqlCommand
                {
                    Connection = myConn
                };
                myConn.Open();

            
                addMessage.Parameters.AddWithValue("@message", message);
                addMessage.Parameters.AddWithValue("@id", 1);

                addMessage.CommandText = ("[spMessageUpdate]");
                addMessage.CommandType = System.Data.CommandType.StoredProcedure;

                addMessage.ExecuteNonQuery();
                addMessage.Parameters.Clear(); // clear it
            } // using   
        } // Message Update


           public  List<string> GrabEmails(){
            SqlConnection myConn = new SqlConnection(Program.da.cs);
            myConn.Open();

            string query = "SELECT email FROM MailerList WHERE status = 'A'";
            SqlCommand results = new SqlCommand(query, myConn);

            using (SqlDataReader reader = results.ExecuteReader()){
                while (reader.Read())
                {
                    emails.Add(reader.GetString(0));
                }
            }// using

            myConn.Close();
            return emails;
        } // GrabEmails

        public void SendEmail(object sender, EventArgs e){
            //get the Settings from WEB.CONFIG file.

            teamsEmail = ConfigurationManager.AppSettings["emailsender"].ToString();
            teamsEmailPassword = ConfigurationManager.AppSettings["password"].ToString();
            teamsEmailHost = ConfigurationManager.AppSettings["smtpserver"].ToString();
            teamsEmailPort = Convert.ToInt16(ConfigurationManager.AppSettings["portnumber"]);

            Boolean emailIsSSL = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSSL"]);


            //Getting Email Body Text for Newsletter path will need to be updated for whoever is using at this time.
            string FilePath = "../Newsletter.cshtml";
            StreamReader str = new StreamReader(FilePath);
            string MailNews = str.ReadToEnd();
            str.Close();

            string subject = "New Newsletter Available!";

            GrabEmails();

            for(int i = 0; i < emails.Count; i++){

                // email to 
                mailMessage.To.Add(emails[i]);

                // body text IS html so true
                mailMessage.IsBodyHtml = true;

                // the teams email, email subject, email body
                mailMessage.From = new MailAddress(teamsEmail);
                mailMessage.Subject = subject;
                mailMessage.Body = MailNews;

                // Set SMTP, HOST server SMTP detail and PORT
                SmtpClient _smtp = new SmtpClient();
                _smtp.Host = teamsEmailHost;
                _smtp.Port = teamsEmailPort;

                // SSL --> True / False
                // Secure Sockets Layer encryption between server and client
                _smtp.EnableSsl = emailIsSSL;

                // Set Sender UserEmailID, Password
                NetworkCredential _network = new NetworkCredential(teamsEmail, teamsEmailPassword);
                _smtp.Credentials = _network;

                // Send the email we created
                _smtp.Send(mailMessage);

            }

        } // SendEmail
    }
}

Pages/Bio.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class BioModel : PageModel
    {
        private readonly ILogger<BioModel> _logger;

        public BioModel(ILogger<BioModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/CoinGraph.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class CoinGraphModel : PageModel
    {
        public string javaScriptString = "";
        public string coinName ="";
        public string weeklyOnly ="";
        private readonly ILogger<CoinGraphModel> _logger;

        public CoinGraphModel(ILogger<CoinGraphModel> logger)
        {
            _logger = logger;
        }

        public void OnGet(string coin)
        {
            if (coin == "BTCWeekly"){
                weeklyOnly = "weekly";
                coin = "BTC";
                coinName = "BTC";
            }                
            else 
                coinName = coin;       

            javaScriptString = "https://min-api.cryptocompare.com/data/v2/histoday?fsym=" + coin + "&tsym=USD&limit=2000&api_key=d2b3e6d1c2375491a5fdc1edb5d12d98f1d2e0d2b54a5ef2d90c673a9738ee6c";
            javaScriptString = System.Web.HttpUtility.JavaScriptStringEncode(javaScriptString);
        }
    }
}

Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class ContactModel : PageModel
    {
        private readonly ILogger<ContactModel> _logger;

        public ContactModel(ILogger<ContactModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/History.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class HistoryModel : PageModel
    {
        private readonly ILogger<HistoryModel> _logger;

        public HistoryModel(ILogger<HistoryModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using CryptoCanuck.CryptoAPI;
using CryptoCanuck.Models;

namespace CryptoCanuck.Pages
{
    public class IndexModel : PageModel
    {
        public List<PriceDatum> price = new List<PriceDatum>();
        
        // Top24 is the top coins with highest trading volume within last 24 hour
        public List<USD> top24Data = new List<USD>();
        public List<CoinInfo> top24CoinInfo = new List<CoinInfo>();
        public Prices prices = new Prices();

        public Prices totals = new Prices();
        public string symbol;
        public int amount;
        
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGet()
        {           
            await Fetch.GetTop24HCryptoData();
            foreach (Top24Datum top24 in Program.topData.Data)
            {
                if (top24.display != null){
                    top24Data.Add(top24.display.USD);
                    top24CoinInfo.Add(top24.CoinInfo);
                }               
            }
            
        } // OnGet() Created by Rui 

        public async Task OnPostPrices(string symbol, int amount)
        {
            await Fetch.GetPrices(symbol);
            prices = Program.prices;

            this.symbol = symbol;
            this.amount = amount;

            prices.CalcTotal(amount);

            await Fetch.GetTop24HCryptoData();
            foreach (Top24Datum top24 in Program.topData.Data)
            {
                if (top24.display != null){
                    top24Data.Add(top24.display.USD);
                    top24CoinInfo.Add(top24.CoinInfo);
                }               
            }
        } //OnPostPrices
    }
}

Pages/Learn.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class LearnModel : PageModel
    {
        private readonly ILogger<LearnModel> _logger;

        public LearnModel(ILogger<LearnModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Links.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class LinksModel : PageModel
    {
        private readonly ILogger<LinksModel> _logger;

        public LinksModel(ILogger<LinksModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/NewsLetter.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace CryptoCanuck.Pages
{
    public class NewsletterModel : PageModel
    {   
        public string RecentNews;
        public void OnGet() {} // OnGet()
        
    
        public void GetRecentMessage(){
            using (SqlConnection myConn = new SqlConnection(Program.da.cs)){
                SqlCommand getRecentMessage = new SqlCommand
                {
                    Connection = myConn
                };
                myConn.Open();

                getRecentMessage.CommandText = ("[spMostRecentMessage]");
                getRecentMessage.CommandType = System.Data.CommandType.StoredProcedure;

                RecentNews = getRecentMessage.ExecuteNonQuery().ToString();
                getRecentMessage.Parameters.Clear(); // clear it
            } // using
            
        } // SendItOut()
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CryptoCanuck.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Subscription.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using CryptoCanuck.Models;

namespace CryptoCanuck.Pages
{
    public class SubscriptionModel : PageModel{

        public void OnPostSubscribe(string email){
            using (SqlConnection myConn = new SqlConnection(Program.da.cs)){
                SqlCommand addEmail = new SqlCommand
                {
                    Connection = myConn
                };
                myConn.Open();

            
                addEmail.Parameters.AddWithValue("@email", email);
                addEmail.Parameters.AddWithValue("@user_id", 1);

                addEmail.CommandText = ("[spAddEmail]");
                addEmail.CommandType = System.Data.CommandType.StoredProcedure;

                addEmail.ExecuteNonQuery(); // run spAddEmail
                addEmail.Parameters.Clear(); // clear it
            } // using
        } // Subscribe

        public void OnPostUnsubscribe(string emailToUnsubscribe){
            using (SqlConnection myConn = new SqlConnection(Program.da.cs)){
                SqlCommand removeEmail = new SqlCommand{
                    Connection = myConn
                };
                myConn.Open();
 
                removeEmail.Parameters.AddWithValue("@email", emailToUnsubscribe);

                removeEmail.CommandText = ("[spRemoveEmail]"); // WHERE statement takes the emailToUnsubscribe as @email
                removeEmail.CommandType = System.Data.CommandType.StoredProcedure;

                removeEmail.ExecuteNonQuery(); // run spRemoveEmail
                removeEmail.Parameters.Clear(); // clear it

            } // using
        } // Unsubscribe
    } // Subscription Class
} // namespace

Pages/About.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Crypto Canuck</h1>
    <div class="ptest">
        Crypto Canuck is a website invented in 2021 by a group of Web Designing students of Trios College as a part of their class Project.
        Crypto Canuck is a website which displays 100 different coins  its prices,total volume in 24 hours,market capital and percentage in 24 hours,
        so that it is easy to compare different coins easily.

        <p>
            A currency converter that allows you to choose any crypto currency and the amount of that crypto currency (5 BitCoins). The converter will then 
            output the value of said crypto currency, at that amount, in CAD, USD, EUR. JYP, and GBP. The converter uses up to date prices via API.
        </p>

        The historical price  chart shows data of daily ,weekly and monthly data since Aug 15 2015 to Feb 4 2021 with its price and volume.
        
        <p>
            we offer a weekly newsletter that will contain a graph of the last 7 days of bitcoins changes and will feature a message directly from the owner of CrptoCanuck.
        </p>
     </div>
</div>

Pages/Admin.cshtml
@page
@model AdminModel
@{
    ViewData["Title"] = "Admin Page";
}

<div class="text-center" >
    <h1 class="display-4">Newsletter Message</h1>
    <div class="ptest" style="text-align: center;">
        <form asp-asp-page-handler="MessageUpdate">
            <textarea title="message" style="width: 80%;" name="message">Please enter the message you want your users to see.</textarea>
            <input class="contactStyle" type="submit" value="Submit" style="width: 125;" title="Submit">
        </form>
     </div>
</div>
<!-- there would also be a button that runs the SendEmail() that the admin can click when they want to send out a newsletter 
    email blast that will show the Newsletter.cshtml-->

Pages/Bio.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Bio page";
}

<div class="bioContainer">
    This website built by classmates in <b ><a href="https://trios-college.ca/" target="_blank" >triOS College </a> London – Ontario – Canada.</h5> <br><br>
   
    <div class="bioTeamDiv">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/hassan.png" alt="Hassan Abu Hadeer">
        </div>
        <div class="bioDescription ">
            <h5>Hassan Abu Hadeer</h5> 
            <p>
            is a web and mobile development student in triOS College, London Ontario Canada.
            Hassan has over than 15 years of experience in deferent type of organization.
            who have WES evaluated Bachelor of Science Degree, Certificate of Managing Project Baselines 2014,
            Certificate of Training in Professional Project Management Program 2015, Certificate of 
            Training in Estimation Practices for Proposals and Controlled Budgets 2017.<a href="https://www.hassanhadeer.com/" target="_blank" >more .. </a>
           </p>
        </div>
    </div><br>
    <div class="bioTeamDiv">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/shilpa.png" alt="Shilpa">
        </div>
        <div class="bioDescription ">
            <h5>Shilpa Sreekumar Pillai</h5> 
            <p>
            is a web and mobile development student in triOS college, London, Ontario Canada.
            Shilpa has got almost eight years experienc in deferent types of organization.She has completed
            Bachelor of engineering in Electronics&Communication and which has equalency of Canadian Degree.
           </p><br>
        </div>
    </div><br>
    <div class="bioTeamDiv">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/noPhoto.png" alt="Bakish">
        </div>
        <div class="bioDescription ">
            <h5>Bakish Panday</h5>
            <p> 
            loves programming, travelling and playing sports. Currently, pursuing the Application development program at Trios College, London. 
            Previously, spent more than 6 years working in hospitality field and developed very strong problem-solving skills including the quick decision. 
           </p>
           <br>
        </div>
    </div><br>
    <div class="bioTeamDiv">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/razan.png" alt="Razan Hatem">
        </div>
        <div class="bioDescription ">
            <h5>Razan Hatem</h5>
            <p>
            loves biking, drawing, and hiking. 

            also has a passion for technology, so she is studying 

            application development and web design at Trios College. 

            In the past years, she has worked as a draft person, and 

            gained experience in designing. She has a diploma in 

            civil engineering. 
           </p><br>
        </div>
    </div><br>
    <div class="bioTeamDiv">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/nabil.png" alt="Nabil Chaiekh">
        </div>
        <div class="bioDescription ">
            <h5>Nabil Chaiekh</h5>  
            <p>
               loves to go on safaris and travel. 
               he loves  to play guitar to his dog ( who hates it ) .  
               He is studying  in Trios College  as an Application Developer ( Enterprise Web Specialist ). He has  over 15 years of experience in project sales and supply chain management  for warehouse solutions.
           </p><br>
        </div>
    </div><br>
    <div class="bioTeamDiv" style="min-height: 110px;">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/Rui.png" alt="Rui Teng">
        </div>
        <div class="bioDescription ">
            <h5>Rui Teng</h5>
            <p>
                is a web and mobile development student in triOS College, London Ontario Canada.
                Rui has more than 10 years experience with mobile device development, worked most time android based software engineering,
                who has moved to Canada with his family and wants to become a frontend based software developer <a href="https://ruiteng2021.github.io/myprofile/#/" target="_blank" >more .. </a>
           </p>
        </div>
    </div><br>
    <div class="bioTeamDiv"style="min-height: 110px;">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/Josh.png" alt="Joshua Eugenio">
        </div>
        <div class="bioDescription ">
            <h5>Joshua Eugenio</h5>
            <p>
            is a web and mobile development student at triOS College (London campus). He has a passion for sports, gaming, and coding. 
            Josh has over 6 years of working experience most of which has been warehouse related. His dream is to one day meet Scarlett Johansson, and become a developer.
           </p>
        </div>
    </div><br>
    <div class="bioTeamDiv">
        <div class="bioImageDiv">
            <img class="bioImage" src="assets/images/Allaura.png" alt="Allaura Trainor">
        </div>
        <div class="bioDescription ">
            <h5>Allaura Trainor</h5> 
            <p>
            is a web and mobile development student in triOS College, London Ontario Canada.
            Allaura got tired of working in retail and decided to use her love of solving problems and technology
            to her advantage. She enrolled in the web and mobile development in October  of 2019. She hopes to prove herself
            asset in whatever she is participating in and incorperate her natural drive to inspire others to love what they do
            and excel at it.<a href="https://allaura-dev.github.io/ah-portfolio/" target="_blank" >more .. </a>
           </p>
        </div>
    </div><br><br>
</div>

Pages/CoinGraph.cshtml
@page
@model CoinGraphModel
@{
    ViewData["Title"] = "Coin Graph";
}

<script type="text/javascript">
    var BTCweekly = "@Model.weeklyOnly";
    var javaScriptAPI = "@Model.javaScriptString";
    var coinName = "@Model.coinName";
</script>

<div id="graphContainer"></div>

Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact page";
}

<div class="contactDiv">
    <div>
        <p class="text-center">
            Thank you for visiting CryptoCanuck! <br>
            We value our customers more than anything, and your satisfaction is what we aim for! <br> 
            please feel free to contact us   , replay will be send to you within 48 hours if your message matching with our services 
        </p>
    </div>
        <div class="contactMap">
        <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d46680.77341207033!2d-81.19135113167998!3d43.008844242763224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882eed6e240c52b3%3A0x5ef85d3eeea9686!2striOS%20College%20Business%20Technology%20Healthcare%20-%20London%20Campus!5e0!3m2!1sen!2sca!4v1611591183839!5m2!1sen!2sca" 
        width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
        </iframe>
    </div>
    <div class="contactForm">
        <form action="FormToEmail.php" method="post">
            <td><input class="contactStyle" placeholder="your name" type="text" size="30" name="name"></td><br>
            <td><input class="contactStyle" placeholder="your email" type="text" size="30" name="email"></td><br>
            <td><textarea class="textContactStyle" name="comments" placeholder="your message" rows="10" cols="30"></textarea></td><br>
            <td><input class="contactStyle" type="submit" value="Send" title="Send"></td>
        </form>
    </div>

</div>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4 welcome">Welcome to Crypto Canuck</h1>
</div>

<!--<a href="/CoinGraph?coin=BTCWeekly"> Test Code for Allaura</a>-->

<div id="converter">
    <div id="converterForm">
        <form method="POST" asp-page-handler="Prices">
        <label for="crypto">Currency converter:</label>

        <select name="symbol">
            @for(int i = 0; i < Model.top24Data.Count; i++){
                <option name="@Model.top24CoinInfo[i].Name" value="@Model.top24CoinInfo[i].Name">@Model.top24CoinInfo[i].FullName</option>
            }
        </select>
        <input type="number" name="amount">
        <button class="btn btn-default">Enter</button>
        </form>
    </div>
    
    <div id="converterTable">
        <table class="table table-hover">
        <thead>
            <tr>
                <th>Currency</th>
                <th>CAD</th>
                <th>USD</th>
                <th>JPY</th>
                <th>EUR</th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td>@Model.amount @Model.symbol</td>
            <td>$@Model.prices.CAD</td>
            <td>$@Model.prices.USD</td>
            <td>¥@Model.prices.JPY</td>
            <td>€@Model.prices.EUR</td>
        </tr>
        </tbody>
    </table>
    </div>  
</div>

<div id= "graphCoinTable">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Coin</th>
                <th scope="col">Price</th>
                <th scope="col">Total Vol/24H</th>
                <th scope="col">Market Cap.</th>
                <th scope="col">% in 24h </th>
            </tr>
        </thead>
        <tbody>
            @for(int i = 0; i < @Model.top24Data.Count; i++)
            {
                <tr>
                    <th scope="row">@(i+1)</th>
                    <td> 
                        <a class="graphLink" href="/CoinGraph?coin=@Model.top24CoinInfo[i].Name">
                            <img src="https://www.cryptocompare.com/@Model.top24CoinInfo[i].ImageUrl?width=25"> @Model.top24CoinInfo[i].FullName
                        </a>
                    </td>                            
                
                    <td>
                        <a class="graphLink" href="/CoinGraph?coin=@Model.top24CoinInfo[i].Name">
                            @Model.top24Data[i].PRICE
                        </a>
                    </td>
                
                    <td>
                        <a class="graphLink" href="/CoinGraph?coin=@Model.top24CoinInfo[i].Name">
                            @Model.top24Data[i].TOTALVOLUME24HTO
                        </a>
                    </td>

                    <td>
                        <a class="graphLink" href="/CoinGraph?coin=@Model.top24CoinInfo[i].Name">
                            @Model.top24Data[i].MKTCAP
                        </a>
                    </td>
                            
                    <td>
                        <a class="graphLink" href="/CoinGraph?coin=@Model.top24CoinInfo[i].Name">
                            @Model.top24Data[i].CHANGEPCT24HOUR
                        </a>
                    </td>                  
                </tr>
            }
        </tbody>
    </table>
</div>

Pages/Subscription.cshtml
@page
@model SubscriptionModel
@{
    ViewData["Title"] = "Newsletter Page";
}

<div class="text-center">
    <h1 class="display-4">Please subscribe to our newsletter for updates from our team.</h1>
    <div>
        <form method="post" asp-page-handler="Subscribe">
            <input type="email" placeholder="Your email here" style="width: 350px; text-align: center;">
            <input class="contactStyle" type="submit" name="email" value="Subscribe" title="Subscribe" style="width: 125px;"> 
        </form>
    </div>
</div>